### PR TITLE
add oca_dependencies.txt

### PR DESCRIPTION
**Pull request by gurneyalex**
depends on
- [x] https://github.com/OCA/purchase-workflow/pull/77

### CODE REVIEW

**Comment by dreispt** [comment]
Are you sure this has dependencies on `purchase-workflow`?

**Comment by dreispt** [comment]
I can see now that that was added to the `.travis.yml`, and also `server-tools`.
But why?

**Comment by gurneyalex** [comment]
@dreispt `framework_agreement_department` and `purchase_requisition_department` depend on addons from OCA/purchase-workflow. 

Would you rather have the dependencies reverted and these addons moved to OCA/purchase-workflow? (cc @lepistone @jgrandguillaume)

**Comment by dreispt** [comment]
I'm sorry I missed the addition of those dependencies.

IMO dependencies between different repos should be avoided, thus kept to a minimum, to avoid exploding complexity.

But of course that won't be possible all the time. When added, a good explanation should be given. I suggest to be a practice to include in the `dependencies.txt` a comment for each one, explaining why it is needed. This will help people using the modules to learn if they will also need that dependency or not.

In this case, these are mostly usability modules, so I would prefer it they could be kept without other dependencies. But it's a matter of carefully thought good sense, so I'm open to other views.
- Regarding `purchase-workflow`, I feel that the dependency should be reverted, if it's not possible to find a way to avoid it.
- Regarding `server-tools`, in principle those should be technical features and no functional project should depend on it. But I'm not aware of the reason for the dependency, so I would like to know more about it.

**Comment by gurneyalex** [comment]
@dreispt `server_tools` has stuff such as base_field_serialized, server_environment, web_context_tunnel which will lead to a significant amount of projects having a dependency on it. 

regarding requiring an explaniation in oca_dependencies.txt, I'm :-1: since the information is in the various `__openerp__.py` files and responsible people should check for this before installing an addon. I'm all in favor of requesting the addition of a comment in that file for dependencies outside the project.

**Comment by dreispt** [comment]
I see. 
But are `server-tools` required here? 
And can it make sense for the `purchase-workflow` dependent modules to be moved there?

**Comment by lepistone** [comment]
In general, IMO dependencies are a hard, but common and manageable problem. I like to encourage orthogonality and reuse of code, even at the cost of some effort to make dependencies work.

As for `purchase-workflow` and `department`, we could probably reverse it, but we would have the same situation again, reversed. I'm not against such a move, but I don't see a great improvement.

For `server-tools` we should check the `__openerp__.py`, but it could be `web_context_tunnel` or something like that. In any case, I don't see a great problem for that also.

My 2c, thanks!

**Comment by dreispt** [comment]
Status: waiting on https://github.com/OCA/maintainer-quality-tools/pull/159

**Comment by lepistone** [comment]
dependencies are merged, I'm :+1: . Thanks!

**Pull request merged**
