### PR TITLE
Port project_issue_department to v8

### PR DESCRIPTION
**Pull request by dreispt**
Should be merged after ~~https://github.com/OCA/department/pull/6.~~

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Daniel, you are stacking all changes in the same branch. You must use different branches for each PR. I have been also a little lost with git, but see that you can make

_git push origin master:name_of_new_branch_

to push your changes to another branch.

**Comment by dreispt** [comment]
They are dependent on each other, so they should be stacked.
The diff is against current master, so when the parent PR is merged you will see the proper diff.
That's why I wrote "Should be merged after ...".

**Comment by pedrobaeza** [comment]
OK, I'm going to make reviews in order then

**Comment by dreispt** [comment]
Rebased on `master` for cleaner diff and easier merge.
Note that this module depends on `project_department` added by #6.

**Comment by pedrobaeza** [comment]
Thanks for the porting, Daniel

:+1:  (code review)

**Comment by bwrsandman** [comment]
Restarted the build.

**Comment by dreispt** [comment]
@bwrsandman The travis config in these branches is not yet properly configured.

**Comment by bwrsandman** [comment]
Can this wait until the travis config is fixed?

**Comment by dreispt** [comment]
OK, but I hope https://github.com/OCA/maintainer-quality-tools/pull/29 is merged quick :smiley:

**Pull request merged**
