### PR TITLE
 Crm departement improvement (was #21)

### PR DESCRIPTION
**Pull request by dreispt**
Supersedes https://github.com/OCA/department/pull/21

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please take the opportunity to solve little pylint issues.

**Comment by dreispt** [comment]
@pedrobaeza No pylint issues on this PR. Fixing the other issue should go in a separate PR, and in fact we already have #25.

**Comment by pedrobaeza** [comment]
Ok, you should rebase then when #25 is merged.

**Comment by pedrobaeza** [comment]
:+1:

**Comment by dreispt** [comment]
I'm not the commiter of the changes, so I guess I can :+1:

**Pull request merged**
