### PR TITLE
Fix duplicate Department on Analytic Account form

### PR DESCRIPTION
**Pull request by dreispt**
It is already added by https://github.com/OCA/department/blob/8.0/analytic_base_department/analytic_view.xml

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by qtheuret** [comment]
:1:

**Comment by dreispt** [comment]
Afterthought: 
If we were using version number is module, this PR should bump "y", say, from `8.0.1.0` to `8.0.1.1`, so that we know that a module upgrade is needed...

**Comment by pedrobaeza** [comment]
Well, I only change version numbering when a migration script is needed. Git log makes the rest

**Comment by dreispt** [comment]
But that way. after a pull, you have no clue if modules need to be upgraded.

**Comment by pedrobaeza** [comment]
The other way you also have no real clue. People is going to forget to bump version. What I do is an --update=all each time I refresh all repositories, and this way, I also check the sanity of the DB. If there's something broken, then I'll get an error, but this happens in very rare occasions :wink:

**Pull request merged**
