### PR TITLE
Set modules not installable an unported

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Hi, Daniel, we have to set a common agreement, because some people have already make PRs using __unported suffix method. Let's discuss this on list before making any move.

**Comment by dreispt** [comment]
Pedro, as I already pointed out in the ML, the "_unported" suffix wasn't discussed in the ML; on the other hand, the "__unported__" subdir was, so I don't feel this method needed further validation.
But if you prefer, please reopen the discussion on the ML.

**Comment by guewen** [comment]
Sandy told on the ML that he did that to prevent Travis to test the modules and nobody disapproved. Now that other maintainers have started to use the _unported suffix, my opinion is that we should continue like that. BTW, your travis configuration still assumes that the unported modules are suffixed with _unported.

**Comment by dreispt** [comment]
I did remind the former decision on the topic, see https://lists.launchpad.net/openerp-community/msg06256.html.
And you're right: I can now see where the "_unported" string is used. I'll fix it if we settle the "__unported__" approach as acceptable.

**Comment by pedrobaeza** [comment]
So, what are we going to do then:
- Rename module dir with __unported suffix.
- Or move to **unported** dir?

**Comment by guewen** [comment]
Honestly, it seems to me that both do the job and changing now to `__unported__` is a bit more complicated since the migration has used `*_unported` so far. Actually, I have nothing against moving the modules in `__unported__` except that I won't make the changes in the documentation and travis files myself because I already spent _a lot_ of time on this migration and for documenting the process and I can't afford to take time for changing that.

If someone wants to change that, please:
- update the documentation: https://github.com/OCA/maintainers-tools/wiki/Migration-Launchpad-%E2%86%92-GitHub#migration-launchpad--github
- update the Travis config. and change the documentation (point 6) so the example shows a correct example.

What about the projects that have been migrated with `_unported`?

**Comment by pedrobaeza** [comment]
OK, for me it's OK to leave with _unported suffix. The only problem I see with this is that all modules will be listed when you add the repository in the addons_path, that will dissapear when migrations were done. This is even worst if someone forget to put installable flag to False.

Regards.

**Comment by dreispt** [comment]
I just opened a discussion on the ML, and explained why I think the change is worth it. Sorry for insisting, but I honestly think the subdirectory solves things the renaming doesn't.

@pedrobaeza:
Your comment is also a good point I didn't think about.

@guewen:
You sure spent a lot of time on this, and the rework can be unfair: in case the "__unported__" goes ahead I promise you I'll make all the changes that I can.
Projects already moved only need a `git mv` that probably can also be automated with a bash command.

**Comment by guewen** [comment]
Ok :+1: @dreispt @pedrobaeza 
Thanks

**Pull request merged**
