### PR TITLE
[8.0][partner_contact_department] Module to add department info to partners

### PR DESCRIPTION
**Pull request by yajo**
This module extends the functionality of the address book to support departments.

Department is a drop-down field in partner forms, and it refers to contact department in its own company.

@rafaelbn @JavierIniesta @antespi

### CODE REVIEW

**Comment by dreispt** [comment]
This repo mission is too weak. It should be discontinued and split into the several functional areas it relates to. See #50.
IMO this module should be proposed to oca/partner-contact

**Comment by yajo** [comment]
Yikes! I just closed https://github.com/OCA/partner-contact/issues/228 exactly for the opposite opinion.

**Comment by pedrobaeza** [comment]
I have just said the contrary, because this repo exists, but if you say so. Anyway, this module is for v8. This one should also be moved?

**Comment by yajo** [comment]
@pedrobaeza do you agree with putting it in partner-contact?

**Comment by pedrobaeza** [comment]
Well, @dreispt is the PSC member in this, so he should be right. Reopen the other PR then. Sorry for the noise.

**Pull request closed without merging**
