### PR TITLE
Fix view errors after upstream changes

### PR DESCRIPTION
**Pull request by dreispt**
Error found here: https://travis-ci.org/OCA/department/jobs/32045736

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This fails in OCB, but not on standard, but that must be a false positive because a name can't be in uppercase (`name='User'`). Can you please fix?

**Comment by dreispt** [comment]
It's not that simple: the problem is that OCB is not being updated, so the view being extended is now different in OCB and Odoo. :tongue: 
Will have find a workaround for that...

**Comment by pedrobaeza** [comment]
Ah, right, this is 8.0... I just update OCB branch with latest upstream, because there's still nothing of OCB integrated, and relaunch Travis, so now the error must be fixed, but I still find strange to have a field name in uppercase.

**Comment by dreispt** [comment]
Thanks! That fixed it.

@qdeconinck The problem was introduced in commit https://github.com/odoo/odoo/commit/f57787e07ee48268015cd088bfc3dafef7001558.
I believe "names" in view fields should also be frozen when the API is frozen, since changing them can break community modules, as in this case.

@odony Any reason for this particular change? Can it be labelled as a regression?

**Comment by odony** [comment]
@dreispt We try [not to modify views in stable versions](https://github.com/odoo/odoo/wiki/Contributing#what-does-stable-mean) when it can be avoided, but we're still in a stabilization/cleanup phase of 8.0RC1 where some amount of such changes could still happen.
Of course it is always recommended to make "locators" for inheriting a view as robust as possible by keeping them generic (i.e. skip non-essential attributes for the locator element, or use a direct and simple xpath expression without full path).

@pedrobaeza It seems the issue was with a `filter`'s name, not a `field` name. The main use for this attribute is for toggling the filter via action contexts by name (e.g. `search_default_<filter_name>: True`) (and it can be used for inheritance locators, too). There is no precise convention for those names as long as they are unique, although I tend to prefer lowercase too.

**Comment by dreispt** [comment]
Thanks for commenting Olivier.

**Comment by pedrobaeza** [comment]
Yeah, thanks!

**Pull request merged**
