### PR TITLE
Better .coveragerc

### PR DESCRIPTION
**Pull request by dreispt**

### CODE REVIEW

**Comment by yvaucher** [comment]
Waiting on talk https://github.com/OCA/maintainer-quality-tools/pull/67
where it was suggested to add coverage with travis

**Comment by dreispt** [comment]
Closed as obsolete with the merge of <s>https://github.com/OCA/department/pull/13</s> https://github.com/OCA/maintainer-quality-tools/pull/67.

**Comment by yvaucher** [comment]
@dreispt you certainly mean merge #12 ? Otherwise some people will loop forever on this PR :smiley:

**Comment by dreispt** [comment]
Yes, I referred to the wrong PR - fixed.

**Pull request closed without merging**
